// Configuration file for the application

// The URL generated by deploying the Google Apps Script
// FOLLOW THE README.MD INSTRUCTIONS TO GET THIS URL!
const GAS_URL = "PASTE_YOUR_URL_HERE";

// Don't change this
window.GAS_URL = GAS_URL;
