// Configuration file for the application

// The URL generated by deploying the Google Apps Script
// FOLLOW THE README.MD INSTRUCTIONS TO GET THIS URL!
const GAS_URL = "https://script.google.com/macros/s/AKfycbzsXXtKDmZ9hp4tZ6i0vi6cqAN-8qbgMF8X39rr14DHatCctI40EP9nmCYZqwcLtxAo/exec";

// Don't change this
window.GAS_URL = GAS_URL;
