// Configuration file for the application

// The URL generated by deploying the Google Apps Script
// FOLLOW THE README.MD INSTRUCTIONS TO GET THIS URL!
const GAS_URL = "https://script.google.com/macros/s/AKfycbzUPglAlKEjOsBwd_zhpZSfjPVIHWoRvCPHoY1VasgUyrl6yfCksQH2VKJ-WSTUewIZLA/exec";

// Don't change this
window.GAS_URL = GAS_URL;
